language: ruby
install:
  - bundle install

script: bundle exec rake site:deploy

env:
  global:
    secure: "vuPCZcvlLR0tkAlMEtru2A/E2xaS7mt6AgRl7lYzefn0yr04sXauElahy0/H5vlRs1Z8EzqsVjHBNZhYqOi+IYKYj5KZULCbcWZwE/3fKXuBAk6jil3z7S3tkxyGgYcz1n/KKn2lR2w7NnLNBeYWuxsRWzo1sgmTpUVCnQEFdAdchjbgP9EZjvOwBG1sojbxCJahR2eNWNRHeoj2pXYXVB2QQAJsP9eIdOujbYkgODS314017EqEGxwoJ9DF09iYmpjGLrAA3aLOT33AbXXpMRJGQgy6Ky/ADfMNzJKVgJY4UHP3zNw5k2RVS00iqSSwOxnl1oalGKw0nGTLWUacg/xc5Ib8ZR92VHFQzHTRFRT5qOiPMWeqF4roemIAL7rmPVFETyWYzaI5x+7nRZHzMcDXZKbaa88aG9uUsjkaILVChTJLFPS7wQakczzAqxIMmR1vvMJLLuPO/0tPdFP10mH0jK9gEhX2/gQfOPQRF2PZ0tFlppD49vTSGVhCt4JHQ8JLJ131gSXt5gZNsZ7pHsvxvLtE62dg53D5cDfL5y6PlO99ewD8cPck2paMEtwrT01sYBrooS08bBmmqKvAsDH8snPPnFyX4ZiP9w2xkDxwktbjIdjtiBWt/IGSFGQHDCcT3qi9TZkS7wBcd+/Cxk4uR/0jlW//mkgyJM6xyVs="
