language: ruby
rvm:
  - 2.1

before_script:
  - chmod +x ./script/cibuild 

script: ./script/cibuild 
branches:
  only:
    - master

env:
  global:
    secure: "eLgvZ1Gm1BCznmIdPWrOVf9Ufp7W2wlIHhtOXhbeTW2E4qHVxip92BsoG3OziKgLgQtkqu34zFnuPcy7MM03U4ZSrR9jVi2qoF8LVV91A0qsEmNKNBtfYY6TMxi4VpQTjBvk2/TlZ3z8wzUWOnO/Gnf71kC2OKcnLKgt+REGkbeW/zHtzmJdcFmCxHbfy2tyel9/0a7SZrPzzrxlZ4u+aia2ZWP2DHp49Y7j+JLaZ1CpuumfLZoGGi7YtcTFAZv4GJqnkq6vXzA6GPzB7l4dN5cAuymlgfKEeTPjb42DSXcIOUTAPftUYZc0ep9rWgYg8l0sOqlL9JbiGdhE8oJXiuEGM6YAO30IMjz38JGCWgHGB/zfzSXwNh1PbyiSZ7v+YIyuKwws+zJb58PVRIP4BFLZgAQB0rhYiK0SUBFbLdAltwwVKjEqBzNdBc9Imdx3y6wLv44L1HOnaeEfe6ipfCGf8H4ba8xisfwl5MXHYc8xxAHqv2/gyt7fpx9j3doc0ev5ZX2vEeR9Qx6zxpGl8EYA75HQQBJ7AjqVzbw1vEFUxnUfWoHldRz2Z7d63r2ZHrlDu/nAVeILozR2UvodR4jTX+enOJgm4coEfUO8yBBmGqZjSEQOq7lNSg0jvv4zSxPL+5BqK+gsR4Gvduixw4f12bCf4hLvDQltbdAJxk4="
