language: ruby

install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "4GmmHVSR6cBzlD1vTOR9lxwjidFQ9a8xzW2EypNsvNKqfDrtBlBdLAqzu68RUhl+uKFJQiv4ga8gcbKVa/3HpWL6TwZshpUwOLTt0qzy1wUI8VV0ixD/a3ECA8GUgMXtekQQsgaeeZSpQKxOJs2N7XcUdnszj5BMqxNer6bcqOvQgMfVQoEauDPc3CEw6S9pelnKSXMF3T8B1Qje7bJ65QbdrbxKdTPpN0Oan4Y6DKt5xyyPIiFUs8q+fdP3axHBbbGgswq6f/IC//HewSwhdHLjUAw+rG9uNNcMtfoznSCSvZMAWFu0N2jxje1MMVKa/NfKPuRGfyH0Q6wW5E+9nU1sjgEvLqHMUDSTkNglUO+ttFM0JKz/Yn9nKQvmaGmCq82omKblOjE4iW8ZECkOEpNhRtidAxFBE8xwOIJdN1qoYWxZW1afgOpirqXgUFLEyC0QYKwdN6Ax/qE9tcyyoNcQuhokU1jWkT91gcmUmAjYu21qap3Z7d/UTiaTPm0/3wE/p3tsp7xKj2lQjHJLrE4APBV3xZ965wlEkTKSjlMRUnkZv7SC02+yTwceA9rRKTcFivGjuKgjCk0f10eS61RXy5j3gV4Z/Hzm1+hvKhjPhENCZXkhkfwPFFU6AJIe4Q5vrJd765r7JqPOxnXrpJKdDtzvRaxgUi+HSUQu1V8="
