language: ruby

install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "m6QEsJ54btlhEFTiZCuJguF7gNofPIT5Xn0SJsW/HhobFGk91gBFiAvWlTj+smycCOHr9EmyZWWst+iTuzcIBlhWkiADiWfDGYQao87FQZtWK4qu/4Wu7flgDmvJDCA5spYwDzgWDA6TOTPW7A8iLFgAnAytpo6oQH10YAnzevrjuvIWcjRP8JC3J2duuLtVNOp2eoW+Kas4zxeYoTGLD9NhAFu6LfHz8zGZeOgvQKXaDiKpaYZe6EO5gehYkGt7YqBuTeSfYdpTTxjuy3v9D3d64/YhSTP+s+mbc/ygBYc6pHv7INsY4faOPWxuWXfoHdDtPfFG9FJVhkVPmbyEGO9TNQ4a+ciL5F7xp1+LNNv2payeS37U1MMCfp4IeizZEVNrI6v1U/71GwWSGQkY5itmVZcJBnjrEk9NRVRz85caA4BBqs1CHgHpuddtSrVs0rldjbEZ0HDavDolpd3TatlzOHXRMEC4+MgVqTpjV8jgK2nNTLB0gLzvRan5kIqjVBo/C1dwvPDLAWVhILl6w3UQprOWl77mSzU7H4gy/ly1YmRVm02sGcXh6fKIJoVEWhB7A9l9IrZcKWF7b081ZY3MQI0cZ+kHQZVCTfB4Z9CiOFi+yu5khWoKXIl++2+hS8Xn7sbp3/OpLkxzCGgxVDIQzwBjMkDlUKilLGpiayc="
