language: ruby
install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "zZbt90ise1Vhzt2Px+loYGfReSlxYapx2yCFW7pp58ZLD5pXZ6DE4+a4n0vUsHb53n+PeM31OijVBTraWF4oy9xijMPxBrgvIz6WkOhDcaiBaXnJxqCCY6NH2xgpB2qY31fbu6iZVj2tmm3bZ6GocrJkwby4As+vQkmre6dDsWn/eR0+j+/guuT0rU//7OSEcaF0daU5I+dP2Y4HDP+Zf1CAXCt426BO7Of+6Epyl4L5uSIZDK5IU1UpMdPxpkoijBj9G38wgfMLyYAL+yVfQ5hcMmfUx4Dg8ZFgHPmpdvHhbPeKRgZ+nb9DC/gOsLIxAPodUxJIVSfecTi/GrvvxXqqOTJuDboXkGxSHdsbJU3I3yiOMtPySrimMDBgirfQol4/cTF1Z9s6T4Cx/q67c19v+TOnon5BLlr6mIiwv+tEZV1kCtgtoVv1WQVFR5SSQS2GKWpZwQ0M4PdGPACHH2rv9kQf+e82ZJu/9W+xtSP7ztnCJMSOjFcA1kxYLFbac+VINj8SS81UFhZm8lSBaDvKTenxCgBq1GdCeymIcYiXWuxqI5Y5k89VB5Sl0awNtiuGEYVdFmsmiFgXJM+vj2dXLQVJS4Mm1Yk1SWa7TvokajNe5QFKx1Z64BQRo1/j9CfR3S/hvqBuubPM/eNngh5vQaKsMASfSKLyDkey9Nw="
