#!/usr/bin/env bash

set -e # halt script on error
git remote rm origin
git remote add origin https://${GIT_NAME}:${GH_TOKEN}@github.com/${USERNAME}/${REPO}.git 


git config --global user.name "${GIT_NAME}"
git config --global user.email "${GIT_EMAIL}"
git config --global push.default simple
git checkout source
bundle exec jekyll build

bundle exec htmlproof ../cesi02.github.io-pages --disable-external --only-4xx --check-favicon --check-html

git checkout master
git rm -rf .
cp -a ../cesi02.github.io-pages/* .
git add -A
git commit -m uw
git push origin source
